spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    spring.upload: DEBUG # 로깅 레벨 설정