spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
    username: root
    password: "ansalsdn15"
    driver-class-name: com.mysql.cj.jdbc.Driver

cloud:
  aws:
    credentials:
      profile-name: spring.s3.test
      access-key: AKIAQWGJYNKVADCGU24F
      secret-key: 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

    region:
      static: ap-northeast-2
    stack:
      auto: false